# Generated by Django 3.1 on 2020-08-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('category', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
